### ISSUE TITLE
AttributeError: module 's3bp' has no attribute 'save_object'

### ISSUE THREAD

**Issue by fontanierh** [shaypal5/s3bp#1]
Hi, it seems like the method `save_object` that is described in the readme does not exist in the module distributed on pip

**Comment by shaypal5** [comment]
Whoa. That's a silly mistake in the code.
Version 0.1.6 is now up on PyPI. The missing method should be there.

Please update me if it's good, so I can close the issue. 

Thanks, :)
Shay
