### ISSUE TITLE
save_object fails when bucket_name and namekey are provided

### ISSUE THREAD

**Issue by dan-hook** [shaypal5/s3bp#2]
When this happens, _get_bucket_and_key doesn't initialize base_directory before using it.

**Comment by shaypal5** [comment]
Fixed in 0.1.7. Please check this for me so I can close the issue. :)

**Comment by shaypal5** [comment]
PR pulled. Check 0.1.8 please.

**Comment by shaypal5** [comment]
Thanks! :)
